int list [];
int a = 1;
int b = 2;
int c = 3;
addLeft(list,a);
addLeft(list,b);
addLeft(list,c);
print_int(list[0]);
print_int(list[1]);
print_int(list[2]);
popLeft(list);
print_int(list[0]);
popLeft(list);
print_int(list[0]);
